name: Create PR from master to main

on:
  push:
    branches:
      - master

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Auto PR from master to main
          title: Merge master into main
          body: |
            This is an automated PR to merge changes from master into main branch.

            Changes included in this PR:
            ${{ github.event.commits[0].message }}
          branch: auto-pr-master-to-main
          base: main
          delete-branch: true
