name: Prepare Release PR

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  create_release_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Create and push release-main
        run: |
          git checkout -b release-main
          git push -f origin release-main

      - name: Raise PR from release-main to main
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          title: "Release PR: release-main -> main"
          body: "This PR merges release-main into main"
          token: ${{ secrets.GITHUB_TOKEN }}
