name: Prepare Release PR

on:
  workflow_dispatch:
  push:
    branches:
      - master

# Add this permissions block
permissions:
  contents: write
  pull-requests: write

jobs:
  create_release_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Add this line to use the token for authentication
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b release-main
          git push origin release-main --force
      - uses: peter-evans/create-pull-request@v5
        with:
          base: main
          title: "Automated Release PR: release-main -> main"
          body: "Automated release changes."
          branch: release-main
          token: ${{ secrets.GITHUB_TOKEN }}
