name: Prepare Release PR

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  create_release_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Create or update release-main from master
        run: |
          # Check if release-main exists on remote
          if git show-ref --quiet refs/remotes/origin/release-main; then
            git branch -D release-main || true
            git checkout -b release-main origin/release-main
          else
            git checkout -b release-main
          fi

          git reset --hard origin/master
          git push --force origin release-main

      - name: Create PR from release-main to main
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          branch: release-main
          title: "Release PR: release-main → main"
          body: |
            This PR merges the latest changes from `master` into `main` via `release-main`.
          token: ${{ secrets.GITHUB_TOKEN }}
